- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: system start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd